config/routes.rb
Rails.application.routes.draw do
	root :to => 'parkings#top'
	get '/map_request', to: 'parkings#map', as: 'map_request'
#root 'parkings#new'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#root '/parkings/top' => 'parkings#top'
resources :users, only: [:show, :edit, :destroy, :update]
resources :parkings, only: [:top, :new, :create, :index, :show, :edit, :destroy, :update]do
   resources :parking_images, only: [:new, :create, :index, :show,:destroy]
end
get '/park_list' => 'users#park_list',as: 'park_list'


 resources :parkings do
    resources :reservations
  end
   get '/reservations' => 'reservations#index'
   get '/lend' => 'reservations#lend'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
          has_many :parkings, dependent: :destroy
          has_many :reservations, dependent: :destroy


  devise :omniauthable, omniauth_providers: %i[facebook]
  # omniauthのコールバック時に呼ばれるメソッド
  def self.from_omniauth(auth)
	    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	      user.email = auth.info.email
	      user.password = Devise.friendly_token[0,20]
	      user.name = auth.info.name
	    end
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
  def facebook
    callback_for(:facebook)
  end
  private
   def callback_for(provider)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
   def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :name])
   end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!
  def show
  	@user = User.find(params[:id])
    # @pakings = Paking.where(user_id: current.user.id)
    # @user.parkings

  end
  def edit
  	@user = User.find(params[:id])
  end
  def update
  	 @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to parking_path
  end

  def park_list
    @user = User.find(current_user.id)
  end

  private

  def user_params
      params.require(:user).permit(:name, :email, :phone_number)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="user" style="text-align:center;">


	<h4>ユーザー編集ページ</h4>

	<%= form_for(@user) do |f|%>

	  <div class="form-group">
		    <div class="form-inline">
			      <label class="form-edit">ユーザー</label>
			      <%= f.text_field :name, :size=>"40%", :class => "form-control" %>
		    </div>
	  </div>

	    <div class="form-group">
		    <div class="form-inline">
			      <label class="form-edit">アドレス</label>
			      <%= f.text_field :email, :size=>"40%", :class => "form-control" %>
		    </div>
	    </div>

	     <div class="form-group">
		    <div class="form-inline">
			      <label class="form-edit">電話番号</label>
			      <%= f.text_field :phone_number, :size=>"40%", :class => "form-control" %>
		    </div>
	    </div>
	  <%= f.submit "変更を保存"%>
	  <p><%= link_to "戻る", user_path %></p>

	<%end%>

</div>

app/views/users/park_list.html.erb
<table class= 'table table-hover table-inverse'>
	<thead>
		<tr>
			<th>パーキングのアドレス</th>
			<th>カータイプ</th>
			<th>値段（１日の料金）</th>
			<th>編集</th>
			<th>消去</th>
			<th>画像編集</th>
		</tr>
	</thead>
	<tbody>
		<% @user.parkings.each do |parking| %>
		<tr>
			<td><%= parking.address %></td>
			<td><%= parking.car_model %></td>
			<td><%= parking.price %>円</td>
			<td><%= link_to "編集", edit_parking_path(parking),class:"btn btn-default" %></td>
			<td><%= link_to "削除", parking_path(parking), method: :delete, data: { confirm: '本当に削除しますか?' },class:"btn btn-default" %></td>
			<td><%= link_to "画像編集", new_parking_parking_image_path(parking),class:"btn btn-default" %></td>



		</tr>
		<%end%>
	</tbody>
</table>

app/views/users/show.html.erb
<div class="user">
	<div class="container">
		<h1 style="text-align:center;">マイページ</h1>



				<table class= 'table table-hover table-inverse' style="text-align:center;">
					<thead>

								<tr>
									<th>ユーザー名</th>
									<td><%= @user.name =%></td>
								</tr>
								<tr>
									<th>アドレス</th>
									<td><%= @user.email =%></td>
								</tr>
								<tr>
									<th>電話番号</th>
									<td><%= @user.phone_number =%></td>
								</tr>
					</thead>
				</table>

			        <p><%= link_to "プロフィール編集", edit_user_path(@user)%></p>
					<p><%= link_to "駐車場管理", park_list_path %></p>
					<p><%= link_to "駐車場使用歴", reservations_path %></p>
					<p><%= link_to "駐車場貸出歴", lend_path %></p>
	</div>
</div>