config/routes.rb
Rails.application.routes.draw do
	root :to => 'parkings#top'
	get '/map_request', to: 'parkings#map', as: 'map_request'
#root 'parkings#new'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#root '/parkings/top' => 'parkings#top'
resources :users, only: [:show, :edit, :destroy, :update]
resources :parkings, only: [:top, :new, :create, :index, :show, :edit, :destroy, :update]do
   resources :parking_images, only: [:new, :create, :index, :show,:destroy]
end
get '/park_list' => 'users#park_list',as: 'park_list'


 resources :parkings do
    resources :reservations
  end
   get '/reservations' => 'reservations#index'
   get '/lend' => 'reservations#lend'

end

app/models/parking_image.rb
class ParkingImage < ApplicationRecord
	belongs_to :parking
	attachment :image
	validates :image, presence: true

end

app/controllers/parking_images_controller.rb
class ParkingImagesController < ApplicationController
	before_action :current_user, only: [:new, :create,:edit, :update, :destroy]

	def new
		@parking_image = ParkingImage.new
		@parking = Parking.find(params[:parking_id])

		@parking_images = ParkingImage.where(parking_id: @parking.id)
	end

	def create
		@parking = Parking.find(params[:parking_id])
	    @parking_image = ParkingImage.new(parking_image_params)
	    @parking_image.parking_id = @parking.id
	    if  @parking_image.save
		    flash[:notice] = "画像投稿成功しました！"
		    redirect_to new_parking_parking_image_path

	    else
	    redirect_to new_parking_parking_image_path
	end
	end

	def index
		@parkings = Parking.find(params[:parking_id])
		@parking_images = ParkingImage.where(parking_id: @parking.id)
	end

	def show
		@parking_image = ParkingImage.find(params[:id])
	end

	def destroy
		@parking = Parking.find(params[:parking_id])
		@parking_image = ParkingImage.find(params[:id])
	    @parking_image.destroy
	    redirect_to new_parking_parking_image_path
	end

	private
    def parking_image_params
        params.require(:parking_image).permit(:image,:parking_id)
    end

end

app/helpers/parking_images_helper.rb
module ParkingImagesHelper
end

app/views/parking_images/index.html.erb
<% @parking_images.each do |parking_image| %>
  <%= attachment_image_tag parking_image,:image, :fill, 100, 100%>
  <%= link_to "削除", parking_path(parking_image), method: :delete, data: { confirm: '本当に削除しますか?' } %>
<% end %>

app/views/parking_images/layouts:_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/parking_images/new.html.erb
 <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

<% @parking_images.each do |parking_image| %>
  <%= attachment_image_tag parking_image,:image, :fill, 300, 300%>
  <P><%= link_to "削除", parking_parking_image_path(@parking, parking_image), method: :delete, data: { confirm: '本当に削除しますか?' } %></P>
<% end %>



<%=form_for [@parking,@parking_image] do |image|%>

 <%= image.attachment_field :image %>

<%= image.submit '写真の追加'%>

<% end %>
<%= link_to "パーキングリストへ戻る", park_list_path %>