config/routes.rb
Rails.application.routes.draw do
	root :to => 'parkings#top'
	get '/map_request', to: 'parkings#map', as: 'map_request'
#root 'parkings#new'

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
#root '/parkings/top' => 'parkings#top'
resources :users, only: [:show, :edit, :destroy, :update]
resources :parkings, only: [:top, :new, :create, :index, :show, :edit, :destroy, :update]do
   resources :parking_images, only: [:new, :create, :index, :show,:destroy]
end
get '/park_list' => 'users#park_list',as: 'park_list'


 resources :parkings do
    resources :reservations
  end
   get '/reservations' => 'reservations#index'
   get '/lend' => 'reservations#lend'

end

app/models/parking.rb
class Parking < ApplicationRecord
    belongs_to :user
    has_many :reservations, dependent: :destroy
    has_many :parking_images, dependent: :destroy

    attachment :parking_image

    geocoded_by :address
    after_validation :geocode, if: :address_changed?
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController
	before_action :current_user, only: [:new, :edit, :update, :destroy]

	def map
	  results = Geocoder.search(params[:address])
	  @latlng = results.first.coordinates
	  # これでmap.js.erbで、経度緯度情報が入った@latlngを使える。
	  # @latingに入っている緯度、経度に近いparkingをデータベースから探してくる
	  respond_to do |format|
	  	format.js
	  end
	end


	def top
	  #@user = User.find(current_user.id)
	  #@parking = @user.parkings
	  #@results = Geocoder.search(@parking)
	  # @latlng = results.first.coordinates

	end

	def new
		@parking = Parking.new
	end

	def create
		@parking = Parking.new(parking_params)
		@parking.user_id = current_user.id
		# 緯度と経度を取得して、カラムにいれる
		#results = Geocoder.search(params[:parking][:address])
	  	#latlng = results.first.coordinates
	  	#@parking.latitude = latlng[0]
	  	#@parking.logitutde = latlng[1]
		@parking.save
		redirect_to new_parking_parking_image_path(@parking)
	end

	def index
		@parkings = Parking.all
	end

	def show
		@parking = Parking.find(params[:id])
		@reservation = Reservation.new
	end

	def edit
		@parking = Parking.find(params[:id])

	end

	def destroy
		@parking = Parking.find(params[:id])
		@parking.user_id = current_user.id
		@parking.destroy
		redirect_to park_list_path
	end

	def update
		 @parking = Parking.find(params[:id])
		 @parking.update(parking_params)
		 redirect_to park_list_path(@parking.id)

	end

	private

    def parking_params
        params.require(:parking).permit(:price, :stock, :car_model, :type, :address, :postal_code, :parking_image, :notes)
    end

end

app/helpers/parkings_helper.rb
module ParkingsHelper
end

app/views/parkings/edit.html.erb
<div style="text-align:center;">
	<%= form_for(@parking) do |parking| %>
<h4>１日あたりの料金</h4>
<%= parking.text_field :price %>円
<h4>利用可能サイズ</h4>
<%= parking.select :car_model, [["軽自動車", "軽自動車"], ["コンパクトカー", "コンパクトカー"], ["セダン", "セダン"], ["SUV", "SUV"], ["ミニバン", "ミニバン"]]%>
<h4>郵便番号</h4>
 <%= parking.text_field :postal_code %>

 <h4>住所</h4>
 <%= parking.text_field :address %>

 <h4>注意事項</h4>
 <%= parking.text_area :notes %>

<p><%= parking.submit '投稿'%></p>
<% end %>
<%= link_to "戻る", park_list_path %>
</div>

app/views/parkings/index.html.erb
<table class= 'table table-hover table-inverse'>
	<thead>
		<tr>
			<th>カータイプ</th>
			<th>貸出名</th>
			<th>住所</th>
			<th>値段（１日の料金）</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		<% @parkings.each do |parking| %>
		<tr>
			<td><%= parking.car_model %></td>
			<td><%= parking.user.name %></td>
			<td><%= parking.address%></td>
			<td><%= parking.price %>円</td>
			<td><%= link_to "予約ページ", parking_path(parking),class:"btn btn-default"%></td>
		</tr>
		<%end%>
	</tbody>
</table>

app/views/parkings/map.js.erb
(function(){
   console.log("検索ボタンが押されました")
   // 位置情報をもつ変数を用意
   let pos = new google.maps.LatLng(
    <%= @latlng[0] %>, //latitude
    <%= @latlng[1] %>  //longitude
   );

   map.setCenter(pos)
   let marker = new google.maps.Marker({
     map: map,
     position: pos,
   });


 })()


// $(function(){
//   $("#submit").click(function(){ //送信ボタンを押すとイベントが発火します
//     $.ajax({
//       type:'GET', // リクエストのタイプはGETです
//       url: '/multi_pin', // URLは"/multi_pin"を指定します
//       dataType: 'json' // データの型はjsonで指定します
//     })
//     .done(function(){
//       // 通信に成功した場合の処理です

//       @parking.forEach(function(){
//         $('.@parking').append(`<li>${parking.address} </li>`);
//       }) //データは配列形式でかえってくるので、forEachで繰り返し処理をします
//     })
//     .fail(function(){
//       // 通信に失敗した場合の処理です
//       alert('検索に失敗しました') // alertで検索失敗の旨を表示します
//     })
//   })
// })

app/views/parkings/new.html.erb
<%= form_for(@parking) do |parking|%>
<div class="container">
	<h1>貸出駐車場登録 </h1>
		  		<div class ="input-froup">

		  			<span class="input-group-addon">利用可能サイズ</span>
		  			<%= parking.select :car_model, [["軽自動車", "軽自動車"], ["コンパクトカー", "コンパクトカー"], ["セダン", "セダン"], ["SUV", "SUV"], ["ミニバン", "ミニバン"]], style: "width:100%;" %>
		  		</div>

		  		<div class ="input-froup">
		  			<span class="input-group-addon">郵便番号</span>
		  			<%= parking.text_field :postal_code , :class => "form-control" %>
		  		</div>

		  		<div class ="input-froup">
		  			<span class="input-group-addon">住所</span>
		  			<%= parking.text_field :address, :class => "form-control" %>
		  		</div>

		  		<div class ="input-froup">
		  			<span class="input-group-addon">１日あたりの料金</span>
		  			<%= parking.text_field :price, :class => "form-control" %>
		  		</div>

		  		<div class ="input-froup">
		  			<span class="input-group-addon">注意事項</span>
		  			<%= parking.text_area :notes, style: "width:100%;" %>
		  		</div>

		  		   <p><%= parking.submit '画像登録へ'%></p>

	<% end %>
</div>

app/views/parkings/show.html.erb
 <% if flash[:danger] %>
      <div class="flash,alert alert-danger">
        <%= flash[:danger] %>
      </div>
    <% end %>


        <% @parking.parking_images.each do |parking_image| %>
               <%= attachment_image_tag parking_image, :image, :fill, 300, 300%>
        <% end %>
                <table class= 'table table-hover table-inverse' style="text-align:center;">
                    <thead>
                        <tr>
                            <th>貸出名</th>
                            <td><%= @parking.user.name %></td>
                        </tr>
                       <tr>
                            <th>住所</th>
                            <td><%= @parking.address %></td>
                        </tr>
                        <tr>
                            <th>値段（１日の料金）</th>
                            <td><%=@parking.price %>円</td>
                        </tr>
                        <tr>
                            <th>カータイプ</th>
                            <td><%=@parking.car_model %></td>
                        </tr>
                        <tr>
                            <th>注意事項</th>
                            <td><%=@parking.notes %></td>
                        </tr>
                    </thead>
                    <tbody>


                    </tbody>
                </table>








<%= form_for [@parking, @reservation] do |f| %>


<%= f.hidden_field :parking_id, value: @parking.id %>

<div class="container">
    <div class='col-md-5'>
        <div class="form-group">
            <div class='input-group date' id='datetimepicker6'>
                <%= f.text_field :start_day, :class => 'form-control', :placeholder => "借りたい日"%>
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
    </div>
    <div class='col-md-5'>
        <div class="form-group">
            <div class='input-group date' id='datetimepicker7'>
                <%= f.text_field :end_day, :class => 'form-control', :placeholder => "返す日"%>
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-calendar"></span>
                </span>
            </div>
        </div>
    </div>
</div>




   <%= f.submit "この日程で予約する", class: "btn btn-danger btn-wide" %>


<% end %>

<script type="text/javascript">
    $(function () {
        $('#datetimepicker6').datetimepicker();
        $('#datetimepicker7').datetimepicker({
            useCurrent: false //Important! See issue #1075
        });
        $("#datetimepicker6").on("dp.change", function (e) {
            $('#datetimepicker7').data("DateTimePicker").minDate(e.date);
        });
        $("#datetimepicker7").on("dp.change", function (e) {
            $('#datetimepicker6').data("DateTimePicker").maxDate(e.date);
        });


    });

</script>
        <%= link_to "戻る", parkings_path,class:"btn btn-default"  %>

app/views/parkings/top.html.erb
<h4>駐車場検索ページ</h4>
<%= form_with url: map_request_path, method: :get do |f|%>

<%= f.text_field :address %>
<%= f.submit '地図表示'%>

<% end %>

<div id='map'></div>

<style>
#map{
  height: 600px;
}
</style>

<script>
	let map
	function initMap(){
		// console.log("initMapが呼び出されました")
		map = new google.maps.Map(document.getElementById('map'), {
			center: {lat: 35.6954806, lng: 139.76325010000005},
			zoom:12
	  	});

	  	var locations = [
	        // ['Title A', <%= @results %>],
	        // ['Title B', <%= @results %>],
	        ['Title A', 35.69496,139.76746000000003],
	    	['Title B', 35.6951212,139.76610649999998],
	    ];
	    var infowindow = new google.maps.InfoWindow;
	    var marker, i;

	    for (i = 0; i < locations.length; i++) {
	        marker = new google.maps.Marker({
	             position: new google.maps.LatLng(locations[i][1], locations[i][2]),
	             map: map
	        });

	        google.maps.event.addListener(marker, 'click', (function(marker, i) {
	             return function() {
	                 infowindow.setContent(locations[i][0]);
	                 infowindow.open(map, marker);
	             }
	        })(marker, i));
	    }
	}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAWd5FVOLqsE5hizPcnsZNl4O5noZnnLPI&callback=initMap" async defer></script>